### ISSUE TITLE
Zrep is not synchronizing user properties

### ISSUE THREAD

**Issue by micw** [bolthole/zrep#11]
This is more or less a feature request: I use a custom snapshot script that makes snapshots via cron and stores snapshot retention time as user property. The problem is that this user property is not replicated. This causes all snapshots to be outdated.
It would be great if zrep could synchronize either all user properties or a configurable list of user properties.

Thank you,
Michael.

**Comment by ppbrown** [comment]
Synchronizing all properties is not doable at all, since zrep itself uses properties. Syncing them all, would break zrep itself.

Syncing an individual list, would be a hack job. I avoid such things, unless the functionality is essential to zrep. In this case, it is not. So, i'm afraid you will have to write your own hackjob outside of zrep ;)
