### ISSUE TITLE
Possibly wrong hard-coded "/tmp" instead of using "$ZREP_RUNDIR".

### ISSUE THREAD

**Issue by ams-tschoening** [bolthole/zrep#123]
typeset tmpfile=$ZREP_RUNDIR/zrep_expire.$$

https://github.com/bolthole/zrep/blob/master/zrep#L1925

vs.

    typeset changecheck tmpfile="/tmp/zrep.$$.c"

https://github.com/bolthole/zrep/blob/master/zrep#L1434

The second line looks like it should use `$ZREP_RUNDIR` as well.

**Comment by ppbrown** [comment]
its not really a bug.
RUNDIR is not strictly synonymous with "temp file".
I created the variable for "things that would normally go under /var/run".
/var/run requires root privs. so I wanted to make sure that, for the few cases zrep gets run by a normal user, it wont just fail, when it doesnt have to.

If anything, I'm not actually sure the first tmpfile example merits use of ZREP_RUNDIR.
And in fact, looking at the comments by ZREP_RUNDIR:
# make sure we dont spew for non-root, so that "zrep status" works

zrep status doesnt need RUNDIR any more. So I'm not sure the variable should even be used at ALL now :-)

Then again, if one wanted to avoid racecondition privilege escalation attempts....
there could be a benefit to putting it under /var/run after all.
Hmm...
