### ISSUE TITLE
Feature Request:  Move SAVE_COUNT to be an explicitly user tunable var

### ISSUE THREAD

**Issue by jhesse** [bolthole/zrep#133]
I'm using zrep-expire as my snapshot expiration utility, so I generally set the SAVE_COUNT=99999 on all my datasets to make sure zrep doesn't accidentally expire snapshots.   I have modified the source to set Z_SAVE_COUNT=99999 but would prefer to mange this with an exported VAR.   I can do that with Z_SAVE_COUNT, but can we move it to the explicitly tunable section at the top of the script.   Not a huge issue, as I can workaround this now.

**Comment by ppbrown** [comment]
hi

erm.

it is already user tunable
you just use
zfs set ....
and change the value set within the file system

btw:
“zrep-expire” is not related to me.
i don’t recommend using it.

**Comment by jhesse** [comment]
Yes.  I understand it is tunable on a per-dataset basis.  I'm talking about tuning the value that gets set on the zrep init call.   

I'm aware that zrep-expire is not related to you.   I had to do a ton of modification to that script to make it useable/safe for me, but at this point I've got it working nicely for retaining snaps at certain intervals over periods of time, e.g. every 20 minutes for the last day, every hour for the last 3 days, every 6 hours for the last 30 days, every day for the last 90 days, every week for the last 3 years, every three months beyond the 3 years.

**Comment by darkpixel** [comment]
@jhesse Not sure if this would work for your situation or not, but I do something similar without interfering with zrep.

I have zfs-auto-snapshot installed (https://github.com/zfsonlinux/zfs-auto-snapshot).  With some minor tuning it can create snapshots for frequently, hourly, daily, weekly, monthly, yearly, etc...and have various retention periods for them.  The zfs-auto-snapshots are actually used by the Samba volume shadowcopy plugin so users can use them to roll back to older versions of files and do self-recovery.  Zrep is used (in my environment) only to make sure we have off-site backups for disaster recovery.  In that case I don't really care about all the varying periods and granularity--just that we take an off-site backup at least once every 24-hours.  Due to the way I have Zrep configured, it ignores the intermediary snapshots created by zfs-auto-snapshots when replicating--so those don't end up on the remote server except for the initial replication with ```-R```.

**Comment by jhesse** [comment]
@darkpixel Thanks for the suggestions.   In my case, I end up actually moving all the intermediary snapshots to both an archive server and another offsite server.   Then I expire those snapshots at each server based on the retention strategies that make senes for that location.   zrep has been really reliable for me and I've got it working really well for my needs.   Just think that it would be generlly useful to have the option to tell zrep not to expire and being able to easily set the save_count variable to a large value in case zrep get's accidentally called without the suggested no-expire flag (separate feature request)..

**Comment by ppbrown** [comment]
ha...
comment to jhesse:
there IS such a thing as too much information. I have TL;DR syndrome just like many others.

If you had deleted most of your comment, and simply made this a one line request, 
"please export Z_SAVE_COUNT into the official user tunable section"
I woudl have done this days ago.

second comment:
you didnt have to change the script. You COULD hav just set Z_SAVE_COUNT in your env.
But in the end, things worked out better for you reporting it.

variable now officially moved to public var section, and renamed to match standard syntax:
ZREP_SAVE_COUNT

945eac3
