### ISSUE TITLE
Documentation improvement: how to access files on destination side

### ISSUE THREAD

**Issue by hostingnuggets** [bolthole/zrep#209]
Hello,

I am using zrep to sync multiple ZFS datasets on a remote server and I was wondering what is best practice if I want to access temporarily the files on that remote server? Let's say I just want to restore a few files from the ZFS dataset and not the whole dataset.

I didn't find such a use case in the official documentation.

Thank you in advance for your feedback.

**Comment by pbrownrobo** [comment]
Hello! And thank you for your interest in zrep.

If I am understanding you correctly, you do not see documentation for this, because it is not possible in the normal sense.
zrep uses ZFS's standard snapshotting mechanisms, to replicate one filesystem, in its entirety, to another filesystem.
You cant say, " Keep filesystem2 always like filesystem1.... oh except for these files".
Thats not how ZFS works.

That being said.. there is a way to likely do what you want to do... and it involves base ZFS functionality.
If you want to just read previous versions of a file... or worst case, copy them off to somewhere ELSE....
ZFS itself can help you.

See https://docs.oracle.com/cd/E71909_01/html/E71919/gprii.html
for documentation of the hidden snapshot directory to access files in the older snapshots that automatically get made as part of the zrep process.

If you routinely want emergency-purpose snapshots kept around longer, what you can do is have a daily snapshot made, and use those to access things.

I forget if you are allowed to directly create snapshots on a destination ZFS filesystem.
You will have to try it out on your own systems to make sure.
Worst case, creating the extra snapshot will break syncing, so you will have to roll back the sync to an earlier point and then resume from there.

**Comment by hostingnuggets** [comment]
Hi @pbrownrobo, thank you for your answer. Probably my question was not quite clear, let me ask differently.

On the remote site of ZREP (where my ZREP snapshots a copied to) I would like to access the ZFS filesystem in order to access a few files of that copy. How is it possible to do that? Right now on my remote site I only see the zfs datasets when I do a `zfs list` but nothing is mounted, meaning I can not access anything.

**Comment by pbrownrobo** [comment]
Ah. so now, it depends on your specific ZFS implementation.

The safest thing to do would be to access the hidden directory on the MASTER side.

Otherwise... it depends whether your ZFS lets you mount a replication target read-only without screwing things up. Some do, some dont.

Suggest you test by:

1. temporarily disabling zrep
2. mount filesystem
3. do your reading
4. umount filesystem
5. manually do one round of zrep sync.
If it works, great. If not, you have to manually roll back the slave to last known good.

well, technically, there is another alternative, where you tell the sync, "force the update and override any changes"

even though technically, you would think a read-only mount wouldnt HAVE any changes.
again, it depends on your ZFS implementation.

**Comment by hostingnuggets** [comment]
So to sum up mounting temporarily the ZFS dataset locally on the remote side of zrep is not recommended even in read-only mode as it could mess up the syncing? 

What is then the safe alternative? Would for example creating a clone of the ZFS dataset and then mount that clone be considered as a safe solution?

**Comment by ppbrown** [comment]
I wouldnt say unsafe.
typically, either it works or it doesnt, and you should know within a few sync attempt iterations. 
There is no risk of data loss that I have heard of. Just the extra hassle of rolling back to prior snapshot on the backup site one time.
So personally, I would go ahead and try it.

The clone idea might work.
But the simplest workaround, if you have the space for it, is to keep the once-a-day snapshots on the master, and peek the snapshot directory there.

**Comment by hostingnuggets** [comment]
I tried a `zfs mount` on the remote side, copied a few files out of the mount and done a `zfs umount`. Then I checked the next day if the zrep sync worked and it did not report any errors. So this procedure seems ok, or I was just lucky. Still I think it might be good to document that part as it could be useful to others.
