### ISSUE TITLE
zrep: 1.6.3 ebuild created and working fine

### ISSUE THREAD

**Issue by samuelbernardo** [bolthole/zrep#33]
I'm sorry to open an issue with only the purpose to give you feedback.
I searched for an alternative way to send you a message in github but I don't find it.

Everything ok with this version. All the syncs work fine.

I've my overlay also published at gentoo now:
https://cgit.gentoo.org/repo/user/ssnb.git/tree/dev-util/zrep/zrep-1.6.3.ebuild

This will help all that like to use zrep in gentoo.

**Comment by ppbrown** [comment]
Thank you for your interest in zrep.
(if you wanted to send me a message you might just use my email, referenced
in the documentation website page :)

Am I correct that I dont have to do anything at this point, because your
file is integrated into gentoo?

Also, i'm wondering why you explicitly mention cpu architecturessuch as x86
and amd64?
This seems to be a bug to me.
zrep is pure script. there is no architecture dependancy. Therefore it
should work on ALL gentoo supported architectures?

Debian has an ARCH=all setting. Does gentoo not have something similar?

**Comment by samuelbernardo** [comment]
Hello,
You're right, it's a bug the architecture dependency that I left there.
In gentoo if a package is available to all architectures than it need toi have them explicitly:
https://devmanual.gentoo.org/keywording/

It only find a comments in changelog with ALLARCHES, but couldn't find some similar to debian arch=all.
Maybe the reason is the source based distribution behavior:
"Important: New packages should be marked as ~arch only upon architectures for which the committing developer has tested."

I'll ask if it's possible in gentoo ebuilds to mention all architectures.

Thanks for your feedback.
