### ISSUE TITLE
Configurable ZFS path

### ISSUE THREAD

**Issue by qcfabrizio** [bolthole/zrep#85]
If all instances of the `zfs` command could be replaced with some variable like `$ZFSCMD` this would make the script more flexible. It would allow the zfs binary to be executed even if its not in the user's PATH and also allows the command to be overridden with another compatible one.

Additionally, this allows for zrep to be run as a non-privileged user on Linux with limited passwordless sudo and SSH on Linux by setting `ZFSCMD` to `sudo zfs` and configuring the sudoers to allow the given user to run `/sbin/zfs`.

I have implemented this on my copy of the source but have noted that you do not accept pull requests. If your stance on this has changed then I would be happy to contribute this change.

**Comment by ppbrown** [comment]
wait...
zfs is normally a USER level command. it is normally in the standard path
on most systems?

IMO if your system is not like this, but you want a user to more easily run
this sort of stuff.. best solution is for the user to adjust their own PATH
variable, and add in /sbin or whatever is appropriate on that system

**Comment by qcfabrizio** [comment]
So the main benefit which is to be gained from this change - at least for my use case - is the ability for zrep to run as an unprivileged user. As mentioned setting the variable to `sudo zfs` allows a user to run zrep with only limited sudo priviledges (even down to only a limited subset of zfs commands).

Giving root passwordless SSH to other hosts on the network doesn't sit right with me and unfortunately on some versions of ZFS there is no support for delegation of privileges and so this change provides a method for running as a non-root user in those scenarios.

Although I am not using it for any other case, there may be the case where this would be beneficial for others if they wanted to wrap the zfs command in another script. I don't see much harm in having this as configurable as with `SSH` and `ZREP_PATH`.

**Comment by ppbrown** [comment]
it would seem reasonable for you to compare this to $SSH and $ZREP_PATH. 
However, they are there for different reasons.
zrep is not a system standard binary; it could concievably be anywhere. So that is why I added a variable for that.
For ssh, I added a variable for it, not because it could be random places, but so that people can automate adding custom flags to it. (ie: SSH="ssh -c none")

In contrast, zfs is a system standard binary, and shouldnt need any unusual customizable options.

Looking at your example of having zrep call "sudo zfs"....
You have the option of allowing  root ssh, but limiting the ssh to only be able to call specific commands. See the openssh documentation  on the authorized_keys file, for how to set that up.
Also.. the interaction between zrep and ssh, is rather... touchy. 
It was very difficult to get ssh to pass through all the options in certain cases.
(that's why I have to resort to using "eval" in a part of the code).
 I suspect that attempting to add sudo into the mix, would screw things up in the pickier cases. since sudo tends to grab direct access to ttys

**Comment by ppbrown** [comment]
in re-reading this, I do see that you mentioned you had gotten this working.
If you want to send me a link to your fork or whateever, I"ll take a look.

**Comment by franck-eyraud** [comment]
Good morning, 

We encountered this issue when using zrep on CentOS 7 systems. zfs command is installed in `/usr/sbin` path when following [official installation instructions](https://github.com/zfsonlinux/zfs/wiki/RHEL-and-CentOS). 

zrep works correctly when run as root, but if we use a non-root zrep user as suggested in the doc, zrep doesn't work any more for this specific reason : any call like `ssh zrep@slave zfs` doesn't find the command.

This is because of some specificity with PATH in [non interactive ssh](https://unix.stackexchange.com/questions/332532/how-to-set-path-when-running-a-ssh-command), so we need to find some workaround; for instance, we created a `/usr/local/bin/zfs` symlink to original command, but if the zrep script would indeed have the zfs command path customized, it would prevent us from modofying the Linux distribution settings.

**Comment by jhesse** [comment]
@franck-eyraud I've also run into this situation where /sbin is not in PATH for various reasons and zrep's calls to simply "zfs" fail.   I've moved to of model of using a wrapper script to manage calls to zrep (to centralize all of my standard VAR settings for the various kinds of zrep uses.   So, I just check the path to see it it contains where zfs is located (always in /sbin in my configs) and if not add it.   Something like this. 

(BASH syntax) 
# /sbin needed in path for zfs particularly when called from a cronjob
    if [[ ":$PATH:" != *":/sbin:"* ]]; then
        export PATH=$PATH:/sbin
    fi

(Before I used a wrapper script I put something like this at the top of the zrep script itself, but I prefer the check style I'm using above in a wrapper script now):
export PATH=$PATH:/sbin  


I get what @ppbrown is saying about the complexity of the interactions between ssh and zfs, so I don't doubt that the suggestion to allow configuring the location of zfs with a zfs command path is a major change request in terms of validating no side effects are created.  

For the issue of using a non-root user for running zrep (in my case on the remote side) I use the method of a command wrapper in the ~/.ssh/authorized_keys file like this 

command="/home/zrep/ssh_command_wrapper" ssh-rsa AAAAB3NzaC1yc2EAAA....

Then the ssh_command_wrapper simply inserts the sudo like this.  
#!/bin/bash
sudo $SSH_ORIGINAL_COMMAND

You need to enable passwordless sudo for that user, and you might want to experiment with limiting the commands that the zrep user can call (using sudoers) depending on your security requirements. 

Hope this helps.

**Comment by ppbrown** [comment]
there are multiple ways of solving this issue, and the best ways do not
involve zrep :)

as one person mentioned, you can add a symlink to zfs in usr local bin.
this isn’t “changing standard linux”. that is exactly what usr local is
for.
for your own “local” customization.

you might also update /etc/profile to add in /usr/sbin
or i guess these days, /etc/environment is better.

again, this is perfectly valid normal system configuration.  it is more
desirable to do this than to modify zrep since users might reasonably want
to call the zfs command directly.

please let me know if updating /etc/environment does not address your
issues.

**Comment by darkpixel** [comment]
FYI - On all my Debian-based installs as well as FreeBSD, zfs is under /sbin.

```
root@ushqzofnas01:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.11 (stretch)
Release:	9.11
Codename:	stretch
root@ushqzofnas01:~# which zfs
/sbin/zfs
root@ushqzofnas01:~# 
```
When backing up to a non-privileged account I have to mess with bashrc on the target (or /etc/bash.bashrc) to include searching in /sbin as it's not included in unprivileged user accounts by default.

**Comment by franck-eyraud** [comment]
Thank you all for your answers. 

It turns out that setting the PATH in the user's `.bashrc` file does solve the issue. No need of the symlink, nor to change the zrep script (for my specific case)

**Comment by ppbrown** [comment]
Thank you for following up
